name: snipeit

on:
  push:
    branches: ["main"]
  pull_request:
   branches: ["main"]
  workflow_dispatch: 
  
jobs:
  start:

    runs-on: ubuntu-latest

    steps:
         # Runs a set of commands using the runners shell
      - name: executing remote ssh commands using ssh key
        uses: Reena221289/cloudsnipeIT@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
        
        
          working-directory: /home/ubuntu
          command: |
            git fetch --all
            git pull origin main
            docker-compose up -d
          comment: building docker containers
